# Generated by Django 5.1.5 on 2025-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_product_product_image_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="product_image",
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
