# Generated by Django 5.1.5 on 2025-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_productimage_product_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_image",
        ),
        migrations.AddField(
            model_name="productimage",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
