# Generated by Django 5.1.5 on 2025-02-01 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_product_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="color_options",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
