# Generated by Django 5.1.5 on 2025-02-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_size_remove_product_size_product_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=200)),
                ("color_code", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="color_options",
        ),
        migrations.AddField(
            model_name="product",
            name="color_options",
            field=models.ManyToManyField(to="product.color"),
        ),
    ]
